development:
  adapter: postgresql
  encoding: unicode
  database: known_buggers_development
  pool: 5
  username: known_buggers

test:
  adapter: postgresql
  encoding: unicode
  database: known_buggers_test
  pool: 5
  username: known_buggers
